#!/bin/bash

if [ ! -z "$IDLE_CHECK_SCHEDULE" ] && ! crontab -l | grep -q "7dtd-idle-check"; then
  echo "$IDLE_CHECK_SCHEDULE /usr/local/bin/7dtd-idle-check > /proc/1/fd/1 2> /proc/1/fd/2" | crontab -
fi
service cron start
/entrypoint.sh "$@"
