version: "3.3"
services:
  image:
    build: .
    image: zobees/7daystodie
    tty: true
    stdin_open: true
    environment:
      STEAMCMD_SKIP_UPDATE: "true"
      SET_UID: "1001"
      SET_GID: "1001"
    ports:
      - "26900-26902:26900-26902"
      - "26900-26902:26900-26902/udp"
    volumes:
      - ./data:/data
