version: "3.3"
services:
  image:
    build: .
    image: zobees/7daystodie
    environment:
      STEAMCMD_SKIP_UPDATE: "true"
    ports:
      - "26900-26902:26900-26902"
      - "26900-26902:26900-26902/udp"
    volumes:
      - ./data:/data
